.PHONY: clean All

All:
	@echo "----------Building project:[ ProblemSet1_1 - Debug ]----------"
	@cd "ProblemSet1_1" && "$(MAKE)" -f  "ProblemSet1_1.mk"
clean:
	@echo "----------Cleaning project:[ ProblemSet1_1 - Debug ]----------"
	@cd "ProblemSet1_1" && "$(MAKE)" -f  "ProblemSet1_1.mk" clean
