.PHONY: clean All

All:
	@echo "----------Building project:[ Mario - Debug ]----------"
	@cd "Mario" && "$(MAKE)" -f  "Mario.mk"
clean:
	@echo "----------Cleaning project:[ Mario - Debug ]----------"
	@cd "Mario" && "$(MAKE)" -f  "Mario.mk" clean
